/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ultranet.view;

import com.ultranet.controller.MainController;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Blaith
 */
public class GUIMain extends javax.swing.JFrame {

    /**
     * Creates new form GUIMain
     */
    public GUIMain(MainController mainController) {
        initComponents();
        listen(mainController);
        menuBar.setOpaque(false); // Permite la transparencia
        menuBar.setBackground(new Color(50, 50, 50, 204)); // 80% 
    }

    public void listen(MainController mainController) {
        jmLeave.addActionListener(mainController);
        jmInventory.addActionListener(mainController);
        jmLogin.addActionListener(mainController);
        jmManageUsers.addActionListener(mainController);
    }

    public void showMessage(String Message) {
        JOptionPane.showMessageDialog(null, Message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmLeave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmInventory = new javax.swing.JMenuItem();
        jmManageUsers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmLogin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ultraNet.png"))); // NOI18N

        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Home");

        jmLeave.setText("Leave");
        jmLeave.setActionCommand("exit");
        jMenu1.add(jmLeave);

        menuBar.add(jMenu1);

        jMenu2.setText("UltraNet");

        jmInventory.setText("Inventory management");
        jmInventory.setActionCommand("adminLogin");
        jmInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInventoryActionPerformed(evt);
            }
        });
        jMenu2.add(jmInventory);

        jmManageUsers.setText("Manage users");
        jmManageUsers.setActionCommand("usersLogin");
        jmManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManageUsersActionPerformed(evt);
            }
        });
        jMenu2.add(jmManageUsers);

        menuBar.add(jMenu2);

        jMenu3.setText("Troubleshoot");

        jmLogin.setText("Users register");
        jmLogin.setActionCommand("login");
        jmLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLoginActionPerformed(evt);
            }
        });
        jMenu3.add(jmLogin);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmInventoryActionPerformed

    private void jmLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmLoginActionPerformed

    private void jmManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManageUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmManageUsersActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIMain().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jmInventory;
    private javax.swing.JMenuItem jmLeave;
    private javax.swing.JMenuItem jmLogin;
    private javax.swing.JMenuItem jmManageUsers;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
