/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ultranet.view.store;

import java.awt.event.ActionListener;

/**
 *
 * @author Blaith
 */
public class StoreButtons extends javax.swing.JPanel {

    /**
     * Creates new form PanelButtons
     */
    public StoreButtons() {
        initComponents();
    }

    public void listen(ActionListener controller) {
        btnBuy.addActionListener(controller);
        btnAddItem.addActionListener(controller);
        btnLeave.addActionListener(controller);
        btnInfo.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuy = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/goBuy.png"))); // NOI18N
        btnBuy.setActionCommand("buy");
        btnBuy.setBorderPainted(false);
        btnBuy.setContentAreaFilled(false);
        btnBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addBuy.png"))); // NOI18N
        btnAddItem.setActionCommand("addItem");
        btnAddItem.setBorderPainted(false);
        btnAddItem.setContentAreaFilled(false);
        btnAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnLeave.setActionCommand("leave");
        btnLeave.setBorderPainted(false);
        btnLeave.setContentAreaFilled(false);
        btnLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/information.png"))); // NOI18N
        btnInfo.setActionCommand("hdwInfo");
        btnInfo.setBorderPainted(false);
        btnInfo.setContentAreaFilled(false);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuy)
                .addGap(18, 18, 18)
                .addComponent(btnAddItem)
                .addGap(18, 18, 18)
                .addComponent(btnInfo)
                .addGap(18, 18, 18)
                .addComponent(btnLeave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLeave)
                    .addComponent(btnAddItem)
                    .addComponent(btnBuy)
                    .addComponent(btnInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLeave;
    // End of variables declaration//GEN-END:variables
}
